优化

diff --git a/Dockerfile-alpine b/Dockerfile-alpine
--- a/Dockerfile-alpine
+++ b/Dockerfile-alpine
@@ -6,48 +6,43 @@ ARG NGINX_VERSION=1.26.2
 ENV TZ "Asia/Shanghai"
 
 # conf
-COPY conf/* /opt/
-COPY fastdfs.sh /home/
+COPY conf/* /home/
+COPY fastdfs.sh /usr/local/bin/
 
 # run
 # install packages
-RUN set -x \
+RUN set -eux \
+    # && sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories \
     && apk update \
-    && apk add --no-cache --virtual .build-deps alpine-sdk build-base perl-dev openssl-dev pcre-dev zlib-dev git
-# git clone libfastcommon / libserverframe / fastdfs / fastdfs-nginx-module
-RUN set -x \
-    && mkdir -p /usr/local/src \
-    && cd /usr/local/src \
+    && apk add --no-cache --virtual .build-deps alpine-sdk build-base perl-dev openssl-dev pcre-dev zlib-dev git \
+    # git clone libfastcommon / libserverframe / fastdfs / fastdfs-nginx-module
+    && mkdir /opt/tmp /opt/fastdfs \
+    && cd /opt/tmp \
     && git clone -b V1.0.68 https://github.com/happyfish100/libfastcommon.git --depth 1 \
     && git clone -b V1.1.28 https://github.com/happyfish100/libserverframe.git --depth 1 \
     && git clone -b V6.09 https://github.com/happyfish100/fastdfs.git --depth 1 \
     && git clone -b V1.23 https://github.com/happyfish100/fastdfs-nginx-module.git --depth 1 \
-    && wget https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
-# build libfastcommon / libserverframe / fastdfs
-RUN set -x \
-    && mkdir /home/dfs \
-    && cd /usr/local/src  \
-    && cd /usr/local/src/libfastcommon \
-    && ./make.sh && ./make.sh install \
-    && cd /usr/local/src/libserverframe \
-    && ./make.sh && ./make.sh install \
-    && cd /usr/local/src/fastdfs \
-    && ./make.sh && ./make.sh install \
-    && cd /usr/local/src \
+    && wget https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz \
     && tar -zxvf nginx-$NGINX_VERSION.tar.gz \
-    && cd /usr/local/src/nginx-$NGINX_VERSION \
-    && ./configure --add-module=/usr/local/src/fastdfs-nginx-module/src \
+    # build libfastcommon, libserverframe, fastdfs
+    && cd /opt/tmp/libfastcommon && ./make.sh && ./make.sh install \
+    && cd /opt/tmp/libserverframe && ./make.sh && ./make.sh install \
+    && cd /opt/tmp/fastdfs && ./make.sh && ./make.sh install \
+    # build nginx and add fastdfs-nginx-module
+    && cd /opt/tmp/nginx-$NGINX_VERSION \
+    && ./configure --add-module=/opt/tmp/fastdfs-nginx-module/src \
     && make && make install \
+    # cp script
+    && cp /opt/tmp/fastdfs/init.d/fdfs_trackerd /usr/local/bin/fdfs_trackerd \
+    && cp /opt/tmp/fastdfs/init.d/fdfs_storaged /usr/local/bin/fdfs_storaged \
+    && chmod +x /usr/local/bin/fastdfs.sh /usr/local/bin/fdfs_trackerd /usr/local/bin/fdfs_storaged \
+    # cleanup
     && apk del .build-deps \
     && apk add --no-cache pcre-dev bash curl tzdata \
-    && chmod +x /home/fastdfs.sh
+    && rm -rf /opt/tmp
 
-RUN cp /usr/local/src/fastdfs/init.d/fdfs_trackerd /etc/init.d/fdfs_trackerd \
-    && cp /usr/local/src/fastdfs/init.d/fdfs_storaged /etc/init.d/fdfs_storaged \
-    && rm -rf /usr/local/src*
-
-VOLUME /home/dfs
+VOLUME /opt/fastdfs
 
 EXPOSE 22122 23000 80
 
-CMD ["/home/fastdfs.sh"]
+CMD ["fastdfs.sh"]
